### ISSUE TITLE
Consider Removing This Package from Ecosystem

### ISSUE THREAD

**Issue by zoffixznet** [tadzik/Task-Star#13]
It's not the first time I see [somebody trying to install Task::Star and having issues](https://irclog.perlgeek.de/perl6/2017-01-14#i_13918126), and the only reason they're trying to install it is because they think Task::Star provides some sort of vital/mandatory modules.

Considering, at least at the current time, Task::Star provides a rather odd collection of modules and most folks wouldn't need ALL of them, my suggestion would be to remove this module from the ecosystem to avoid confusion for users who aren't sure what they need to install.

**Comment by stmuk** [comment]
I think this package should be removed too.  It doesn't contain the same the modules as Rakudo Star (and hasn't done for a long time) and will be confusing to end users for this reason.

Note also I submitted a PR in Feb 2017 to sync with R* which wasn't merged and no longer applies.

https://github.com/tadzik/Task-Star/pull/14

Please either remove Task::Star or rename the module to something less confusing under the Task:: namespace.

**Comment by tadzik** [comment]
Yep, let's drop it then. I think my idea was to just make Star depend on Task::Star which would fix the syncing problem, but since that never happened in the last 4 years or so, I don't think it will.
