### ISSUE TITLE
Unattempted installs

### ISSUE THREAD

**Issue by VSChawathe** [tadzik/Task-Star#4]
If any one module fails to install eg. https://github.com/tadzik/Bailador/issues/22 , installing the leftovers has to be manually reattempted on a one by one basis, eg. https://github.com/cosimo/perl6-lwp-simple/issues/43 , https://github.com/perl6/Perl6-MIME-Base64/issues/3 , https://github.com/perl6/Pod-To-HTML/issues/6 .

**Comment by tadzik** [comment]
Yeah, that's an issue with Panda though. I'm not sure if it should be fixed, but I'll transfer the issue to Panda nonetheless. Thanks!
